package io.github.xpler2.plugin.config

import io.github.xpler2.plugin.bean.XplerEntryBean

object XposedKeepRules {
    const val STATUS_PROVIDER_CLASS_NAME = "XplerStatusProvider"
    const val OUTPUT_PATH = "xposed/proguard-rules.pro"

    fun create(entry: XplerEntryBean): String {
        val entryClassName = entry.xplerHint.resolvedName

        return """
# Generated by xpler2-compiler for Xposed runtime loading.
-keep class $STATUS_PROVIDER_CLASS_NAME {
    public static final $STATUS_PROVIDER_CLASS_NAME INSTANCE;
}
-keepclassmembers,allowobfuscation class $STATUS_PROVIDER_CLASS_NAME {
    <methods>;
}
-keep class $entryClassName {
    public <init>();
    public void initZygote(...);
    public void handleLoadPackage(...);
}
""".trimIndent() + "\n"
    }
}
